---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - "faucet.rules.yml"
scrape_configs:
  - job_name: 'faucet'
    static_configs:
      - targets: ['faucet:9302']
  - job_name: 'faucetconfrpc'
    static_configs:
      - targets: ['faucetconfrpc:59998']
  - job_name: 'gauge'
    static_configs:
      - targets: ['gauge:9303']
  - job_name: 'poseidon'
    static_configs:
      - targets: ['poseidon:9304']
  - job_name: 'poseidon workers'
    static_configs:
      - targets: ['workers:9305']
