name: release

on:
  push:
    branches: main
    tags: 'v*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Build and publish packages
      id: build_and_publish_packages
      run: |
        sudo apt-get update && \
        sudo apt-get install -yq --no-install-recommends curl gcc g++ libev-dev libyaml-dev python3-pip python3.8 python3.8-dev && \
        cd lib/poseidon_api && poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }} && cd ../../ && \
        cd lib/poseidon_cli && poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }} && cd ../../ && \
        cd lib/poseidon_core && poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }} && cd ../../
      if: github.repository == 'iqtlabs/poseidon' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
